# makefile for cargo
[config]
default_to_workspace = false

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.build_swift]
description = "Build the swift code"
script_runner = "@shell"
script = """
cd server-swift
swift build -c release
cp .build/release/azookey-server.lib ../
"""

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build_x86]
command = "cargo"
args = ["build", "-p", "azookey-windows", "--target=i686-pc-windows-msvc"]

[tasks.post_build]
description = "Copy necessary files"
script_runner = "powershell"
script_extension = "ps1"
script  = """
cp server-swift/.build/x86_64-unknown-windows-msvc/release/azookey-server.dll target/debug/
cp server-swift/llama.dll target/debug/

cp $env:APPDATA/../Local/Programs/Swift/Runtimes/*/usr/bin/* target/debug/

cp -Recurse -Force server-swift/azooKey_emoji_dictionary_storage/EmojiDictionary target/debug/
cp -Recurse -Force server-swift/azooKey_dictionary_storage/Dictionary target/debug/
"""

[tasks.flow]
description = "Run the flow"
dependencies = [
    "format",
    "build_swift",
    "build",
    "build_x86",
    "post_build"
]